#! /bin/sh

# hsc2hs doesn't allow us to replace the template file, so do it here.
# (It has a --template option, but it's cumulative.)

for file
do
	ed - $file >/dev/null <<EOF
1 s:".*/:"
w
EOF
done
